#!/usr/bin/env bash

for file in ~/Downloads/*; do
    case "$file" in
    *.zip|*.rar) mv $file ~/Downloads/Archives;; 
    *.doc|*.docx|*.odt|*.rtf|*.txt|*.md) mv $file ~/Downloads/Documents;;
    *.ppt|*.pptx|*.odp) mv $file ~/Downloads/Documents;;
    *.xls|*.xlsx|*.ods|*.csv) mv $file ~/Downloads/Spreadsheets;;
    *.mp4|*.mkv|*.avi|*.mov|*.wmv) mv $file ~/Downloads/Videos;;
    *.mp3|*.wav|*.wma) mv $file ~/Downloads/Music;;
    *.jpg|*.jpeg|*.bmp|*.png|*.gif|*.webp) mv $file ~/Downloads/Pictures;;
    *.exe|*.msi|*.dmg|*.rpm) mv $file ~/Downloads/Programs;;
    esac
 
done
