#!/usr/bin/env bash

D="/home/annalage/Downloads"

inotifywait -m -e close_write -e moved_to --format "%w%f" "$D" | while read -r file; do 
    case "$file" in
    *.zip|*.rar) folder="Archives";;
    *.doc|*.docx|*.odt|*.rtf|*.txt|*.md) folder="Documents";;
    *.ppt|*.pptx|*.odp) folder="Presentations";;
    *.xls|*.xlsx|*.ods|*.csv) folder="Spreadsheets";;
    *.mp4|*.mkv|*.avi|*.mov|*.wmv) folder="Videos";;
    *.mp3|*.wav|*.wma) folder="Music";;
    *.jpg|*.jpeg|*.bmp|*.png|*.gif|*.webp) folder="Pictures";;
    *.exe|*.msi|*.dmg|*.rpm) folder="Programs";;
    esac

    if [[ -f "$file" ]]; then
    mkdir -p "$D/$folder" && mv "$file" "$D/$folder"
    fi
 
done
